require('basic')
require('autocmd')
require('run-code')
require('basic-map')
require('plugins')

require('plugins/rainbow')
require('plugins/markdown-preview')
require('plugins/asyncrun')
require('plugins/suda')
require('plugins/alpha-nvim')
require('plugins/telescope')
require('plugins/vim-vsnip')
require('plugins/nvim-cmp')
require('plugins/lualine')
require('plugins/gitsigns')
require('plugins/nvim-treesitter')
require('plugins/vimtex')

vim.cmd([[colorscheme gruvbox-material]])
