require('basic')
require('autocmd')
require('run-code')
require('basic-map')
require('plugin')

require('plugin/rainbow')
require('plugin/markdown-preview')
require('plugin/asyncrun')
require('plugin/suda')
require('plugin/alpha-nvim')
require('plugin/telescope')
require('plugin/vim-vsnip')
require('plugin/nvim-cmp')
require('plugin/lualine')

vim.cmd([[colorscheme gruvbox]])
