#!/bin/sh
tmp_bg=$(mktemp /tmp/screen-XXXX.png)
lock_icon="$HOME/.config/i3/avatars.png"
resolution=$(xrandr | grep 'current' | sed -E 's/.*current\s([0-9]+)\sx\s([0-9]+).*/\1x\2/')
ffmpeg -f x11grab -video_size "${resolution}" -y -i "$DISPLAY" -i "${lock_icon}" -filter_complex "boxblur=5:1,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" -vframes 1 "${tmp_bg}" -loglevel quiet
i3lock -e -i "${tmp_bg}"
rm "${tmp_bg}"
